dist: trusty

sudo: required

services:
  - mysql

language: go

os:
    - linux

go:
  - 1.9
  - "1.10"
  - tip

matrix:
  allow_failures:
  - go: tip

env:
   - PREST_PG_USER=root PREST_PG_DATABASE=prest PREST_PG_PORT=3306 PREST_CONF=$TRAVIS_BUILD_DIR/testdata/prest.toml

before_script:
    - sh testdata/schema.sh
    - go get -v -d ./...

script:
    - sh test.sh